# Generated by Django 4.1.3 on 2022-11-23 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsignsforrepair',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='rsm_api.area'),
        ),
        migrations.AlterField(
            model_name='roadsignsforrepair',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localities', to='rsm_api.locality'),
        ),
        migrations.AlterField(
            model_name='roadsignsforrepair',
            name='sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signs', to='rsm_api.roadsign'),
        ),
    ]
